name: Publicar o site escrito em Gatsby
        
language: node_js

before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: script
  script: cd site-gatsby && yarn install && yarn run deploy_public_pref_unugly
  skip_cleanup: true
  on:
    branch: beta